# .github/workflows/main.yml
name: Python Workflow

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python -m pip install poetry
      - run: python -m poetry install
        run: python -m poetry run coverage run -m pytest
      - run: python -m poetry run isort --diff .
      - run: python -m poetry run black --check .
      - run: python -m poetry run mypy -p finpack
